#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Hibiki Chiba
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
for line in sys.stdin :
	try :
		if int(line) % 2 == 1 :
			ans += int(line)
		elif int(line) % 2 == 0 :
			ans -= int(line)
	except :
		ans += float(line)

print(ans)
